-- Insert sample projects for testing
INSERT OR IGNORE INTO projects (
  title, 
  description, 
  category, 
  funding_type, 
  amount, 
  languages,
  app_link,
  website_link,
  youtube_link,
  thumbnail,
  business_model,
  team_info,
  contact_email,
  status
) VALUES 
(
  '스마트 헬스케어 앱',
  'AI 기반 건강 관리 플랫폼으로 개인 맞춤형 건강 솔루션을 제공합니다.',
  '헬스케어',
  '투자',
  5000,
  '한국어, 영어',
  'https://play.google.com/store',
  'https://example.com',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'https://via.placeholder.com/400x300/4F46E5/FFFFFF?text=Healthcare+App',
  '프리미엄 구독 모델 - 월 9,900원',
  '의료 전문가 3명, 개발자 5명으로 구성된 팀',
  'contact@healthcare.com',
  'active'
),
(
  '소셜 커머스 플랫폼',
  '지역 상권과 소비자를 연결하는 O2O 플랫폼입니다.',
  'O2O',
  '수익분배',
  8600,
  '한국어, 중국어, 일본어',
  'https://apps.apple.com/app',
  'https://commerce.example.com',
  '',
  'https://via.placeholder.com/400x300/10B981/FFFFFF?text=Commerce+Platform',
  '거래 수수료 5% + 광고 수익',
  '창업 경험 10년+ 대표, 마케팅/개발 팀 구성',
  'team@commerce.com',
  'active'
),
(
  '에듀테크 학습 플랫폼',
  '학생과 교사를 위한 스마트 학습 관리 시스템입니다.',
  '교육',
  '창업희망',
  3000,
  '한국어, 영어',
  '',
  'https://edutech.example.com',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'https://via.placeholder.com/400x300/F59E0B/FFFFFF?text=EduTech+Platform',
  'B2B SaaS 모델 - 학교당 월 50만원',
  '교육 전문가 2명, 풀스택 개발자 3명',
  'info@edutech.com',
  'active'
);
